StylesPath = .github/styles

Vocab = Docs

MinAlertLevel = warning

IgnoredScopes = code, tt, pre, span

Packages = Google

[*.md]
BasedOnStyles = Anyscale, Vale, Google

# Disable checks for e.g. '95th'; Google.Ordinal forces users
# to spell out 'ninety fifth'.
Google.Ordinal = NO
Google.Units = NO

BlockIgnores = {#[\w-]*}
