steps:
  - label: ":mag: Verify checkout"
    command: |
      echo "--- Repo:   $$BUILDKITE_REPO"
      echo "--- Branch: $$BUILDKITE_BRANCH"
      echo "--- Commit: $$BUILDKITE_COMMIT"
      git log -1 --oneline
      echo "checkout ok"
    agents:
      queue: smallg
    timeout_in_minutes: 5
    retry:
      automatic: false
