package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &ProjectResource{}
	_ resource.ResourceWithConfigure   = &ProjectResource{}
	_ resource.ResourceWithImportState = &ProjectResource{}
)

// NewProjectResource creates a new project resource.
func NewProjectResource() resource.Resource {
	return &ProjectResource{}
}

// ProjectResource defines the resource implementation.
type ProjectResource struct {
	client *Client
}

// ProjectResourceModel describes the resource data model.
type ProjectResourceModel struct {
	// Identity
	ID types.String `tfsdk:"id"`

	// Cloud reference - mutually exclusive
	CloudID   types.String `tfsdk:"cloud_id"`
	CloudName types.String `tfsdk:"cloud_name"`

	// Core attributes
	Name                   types.String `tfsdk:"name"`
	Description            types.String `tfsdk:"description"`
	InitialClusterConfigID types.String `tfsdk:"initial_cluster_config_id"`

	// Nested collaborators
	Collaborators []ProjectCollaboratorModel `tfsdk:"collaborator"`

	// Computed fields
	CreatorID       types.String `tfsdk:"creator_id"`
	CreatedAt       types.String `tfsdk:"created_at"`
	LastUsedCloudID types.String `tfsdk:"last_used_cloud_id"`
	IsDefault       types.Bool   `tfsdk:"is_default"`
	DirectoryName   types.String `tfsdk:"directory_name"`
}

// ProjectCollaboratorModel represents a project collaborator.
type ProjectCollaboratorModel struct {
	Email           types.String `tfsdk:"email"`
	PermissionLevel types.String `tfsdk:"permission_level"`
	IdentityID      types.String `tfsdk:"identity_id"` // Computed
	UserID          types.String `tfsdk:"user_id"`     // Computed
}

// Metadata returns the resource type name.
func (r *ProjectResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project"
}

// Schema defines the schema for the resource.
func (r *ProjectResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages an Anyscale Project. Projects organize workspaces and resources within a cloud.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The unique identifier of the project.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},

			// Cloud reference (mutually exclusive)
			"cloud_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "The cloud ID for this project. Either `cloud_id` or `cloud_name` must be specified.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"cloud_name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "The cloud name for this project. Either `cloud_id` or `cloud_name` must be specified. Will be resolved to cloud_id.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},

			// Core attributes
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The name of the project. The API reserves the names `-` and `default` (case-insensitive); using either fails the request.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.NoneOfCaseInsensitive("-", "default"),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Description of the project. If not provided, a default description will be auto-generated by the API. The Anyscale API has no endpoint to update a project's description in place, so explicitly changing this value to something different forces replacement of the project; omitting it (letting the API-generated value persist) never does.",
				PlanModifiers: []planmodifier.String{
					// Not RequiresReplace: that fires on any unrelated update when description is omitted, since unknown reads as "changed" before UseStateForUnknown resolves it.
					stringplanmodifier.RequiresReplaceIfConfigured(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"initial_cluster_config_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "The initial cluster configuration ID to use for workspaces in this project. This is a create-time-only input (API field `cluster_config`): the provider does not read its current value back from the API after creation, so it is not refreshed on `terraform plan`/`refresh` and will always be null immediately after `terraform import`. Changing it forces replacement of the project.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},

			// Computed fields
			"creator_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The ID of the user who created the project.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Timestamp when the project was created.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_used_cloud_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The ID of the cloud last used by this project.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"is_default": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Whether this is the default project for the organization.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"directory_name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The directory name used for this project's storage.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},

		Blocks: map[string]schema.Block{
			"collaborator": schema.ListNestedBlock{
				MarkdownDescription: "Collaborators with access to this project. Can be added, removed, or modified in-place.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"email": schema.StringAttribute{
							Required:            true,
							MarkdownDescription: "Email address of the collaborator.",
						},
						"permission_level": schema.StringAttribute{
							Required:            true,
							MarkdownDescription: "Permission level granted to the collaborator: `owner`, `write`, or `readonly`. See the [Project guide](../guides/project.md) for how this differs from `anyscale_policy_binding`.",
							Validators: []validator.String{
								stringvalidator.OneOf("owner", "write", "readonly"),
							},
						},
						"identity_id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The identity ID of the collaborator (computed).",
						},
						"user_id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The user ID of the collaborator (computed).",
						},
					},
				},
			},
		},
	}
}

// Configure adds the provider configured client to the resource.
func (r *ProjectResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*Client)
	if !ok {
		AddConfigError(&resp.Diagnostics, "Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T. Please report this issue to the provider developers.", req.ProviderData))
		return
	}

	r.client = client
}

// Create creates the resource and sets the initial Terraform state.
func (r *ProjectResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ProjectResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Validate cloud reference
	if plan.CloudID.IsNull() && plan.CloudName.IsNull() {
		AddConfigError(&resp.Diagnostics, "Cloud Reference Required",
			"Either 'cloud_id' or 'cloud_name' must be specified to create a project.")
		return
	}

	if !plan.CloudID.IsNull() && !plan.CloudName.IsNull() {
		AddConfigError(&resp.Diagnostics, "Conflicting Cloud Reference",
			"Cannot specify both 'cloud_id' and 'cloud_name'. Please provide only one.")
		return
	}

	// Resolve cloud_name to cloud_id if needed (for API call only, don't modify plan)
	cloudID := plan.CloudID.ValueString()
	if plan.CloudID.IsNull() && !plan.CloudName.IsNull() {
		cloudName := plan.CloudName.ValueString()
		tflog.Info(ctx, "Resolving cloud_name to cloud_id", map[string]any{"cloud_name": cloudName})

		resolvedID, err := ResolveCloudNameToID(ctx, r.client, cloudName)
		if err != nil {
			AddConfigError(&resp.Diagnostics, "Cloud Name Resolution Failed",
				fmt.Sprintf("Failed to resolve cloud name '%s' to ID: %s", cloudName, err.Error()))
			return
		}
		cloudID = resolvedID
		// Don't set plan.CloudID here - keep cloud_name in state
	}

	// Build create request
	desc := plan.Description.ValueString()
	createReq := CreateProjectRequest{
		Name:          plan.Name.ValueString(),
		ParentCloudID: cloudID,
		Description:   &desc,
	}

	if !plan.InitialClusterConfigID.IsNull() {
		configID := plan.InitialClusterConfigID.ValueString()
		createReq.InitialClusterConfigID = &configID
	}

	// Marshal request to JSON
	reqBody, err := MarshalRequestBody(createReq)
	if err != nil {
		AddJSONError(&resp.Diagnostics, "marshal", "project create request", err)
		return
	}

	tflog.Debug(ctx, "Creating project", map[string]any{
		"name":            createReq.Name,
		"parent_cloud_id": createReq.ParentCloudID,
	})

	// Create project
	projectResp, err := DoRequestAndParse[ProjectResponse](
		ctx,
		r.client,
		"POST",
		"/api/v2/projects",
		reqBody,
		http.StatusCreated,
		http.StatusOK,
	)
	if err != nil {
		AddAPIError(&resp.Diagnostics, "create project", err)
		return
	}

	projectID := projectResp.Result.ID
	plan.ID = types.StringValue(projectID)

	tflog.Info(ctx, "Project created successfully", map[string]any{"project_id": projectID})

	// Create collaborators if specified
	if len(plan.Collaborators) > 0 {
		if err := r.createCollaborators(ctx, projectID, plan.Collaborators); err != nil {
			AddAPIError(&resp.Diagnostics, "add collaborators (project created)", err)
			// Continue to read state even if collaborators failed
		}
	}

	// Read back full state
	if err := r.readProject(ctx, projectID, &plan); err != nil {
		AddAPIError(&resp.Diagnostics, "read project after create", err)
		return
	}

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Read refreshes the Terraform state with the latest data.
func (r *ProjectResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ProjectResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectID := state.ID.ValueString()

	// Read project
	if err := r.readProject(ctx, projectID, &state); err != nil {
		if strings.Contains(err.Error(), "404") || strings.Contains(err.Error(), "not found") {
			tflog.Warn(ctx, "Project not found, removing from state", map[string]any{"project_id": projectID})
			resp.State.RemoveResource(ctx)
			return
		}

		AddAPIError(&resp.Diagnostics, "read project", err)
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *ProjectResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state ProjectResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectID := state.ID.ValueString()

	tflog.Info(ctx, "Updating project collaborators", map[string]any{"project_id": projectID})

	// Only collaborators can be updated; other fields require replacement
	if err := r.syncCollaborators(ctx, projectID, plan.Collaborators, state.Collaborators); err != nil {
		AddAPIError(&resp.Diagnostics, "update collaborators", err)
		return
	}

	// Read back full state
	if err := r.readProject(ctx, projectID, &plan); err != nil {
		AddAPIError(&resp.Diagnostics, "read project after update", err)
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *ProjectResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ProjectResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectID := state.ID.ValueString()

	tflog.Info(ctx, "Deleting project", map[string]any{"project_id": projectID})

	// Delete project
	_, err := DoRequestRaw(
		ctx,
		r.client,
		"DELETE",
		fmt.Sprintf("/api/v2/projects/%s", projectID),
		nil,
		http.StatusOK,
		http.StatusNoContent,
		http.StatusNotFound,
	)
	if err != nil {
		if strings.Contains(err.Error(), "status 409") {
			resp.Diagnostics.AddError(
				"Project Has Active Resources",
				fmt.Sprintf("Cannot delete project %s: it still has running clusters or workspaces. Terminate all clusters and workspaces in this project, then retry. (%s)", projectID, err.Error()),
			)
			return
		}
		AddAPIError(&resp.Diagnostics, "delete project", err)
		return
	}

	tflog.Info(ctx, "Project deleted successfully", map[string]any{"project_id": projectID})
}

// ImportState imports the resource into Terraform state.
func (r *ProjectResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	projectID := req.ID

	// Read the project first (with a still-empty model.Collaborators, so
	// readProject's own gate skips fetching them here) so a bad project ID
	// surfaces as a clean "not found" instead of an unrelated-looking
	// collaborators-endpoint error.
	var model ProjectResourceModel
	if err := r.readProject(ctx, projectID, &model); err != nil {
		if strings.Contains(err.Error(), "404") || strings.Contains(err.Error(), "not found") {
			AddConfigError(&resp.Diagnostics, "Project Not Found",
				fmt.Sprintf("No project exists with ID %q.", projectID))
			return
		}
		AddAPIError(&resp.Diagnostics, "read project for import", err)
		return
	}

	// readProject only fetches collaborators when the incoming model already
	// has some - correct for ordinary refresh, where it stops a project
	// managed with no collaborator block from perpetually diffing against
	// the API's auto-added creator-owner collaborator, but fatal for import:
	// there is no prior state yet, so that heuristic can never see "was
	// configured" and would silently drop every real collaborator, no
	// matter how many exist. Import is the one lifecycle point where
	// recovering them unconditionally is unambiguous - there's no prior
	// state to confuse "recovered at import" with "never configured" (same
	// reasoning as CC12 in resource_compute_config.go's ImportState). Fetch
	// them explicitly here; every later refresh re-fetches them again on its
	// own since this seeds a non-empty list into state.
	collaborators, err := r.getCollaborators(ctx, projectID)
	if err != nil {
		AddAPIError(&resp.Diagnostics, "read collaborators for import", err)
		return
	}
	model.Collaborators = collaborators

	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

// Helper functions

// readProject reads a project's details and collaborators into the model.
func (r *ProjectResource) readProject(ctx context.Context, projectID string, model *ProjectResourceModel) error {
	tflog.Debug(ctx, "Reading project", map[string]any{"project_id": projectID})

	// Get project details
	projectResp, err := DoRequestAndParse[ProjectResponse](
		ctx,
		r.client,
		"GET",
		fmt.Sprintf("/api/v2/projects/%s", projectID),
		nil,
		http.StatusOK,
	)
	if err != nil {
		// Check for 404
		if strings.Contains(err.Error(), "404") {
			return fmt.Errorf("project not found (404)")
		}
		return fmt.Errorf("failed to get project: %w", err)
	}

	// Map to model
	result := projectResp.Result
	model.ID = types.StringValue(result.ID)
	model.Name = types.StringValue(result.Name)

	// Handle cloud reference based on what user provided:
	// - If cloud_name was provided: keep it, don't set cloud_id
	// - If cloud_id was provided OR this is import (both null): set cloud_id from API
	if model.CloudName.IsNull() {
		model.CloudID = types.StringValue(result.ParentCloudID)
	}

	if result.Description != nil {
		model.Description = types.StringValue(*result.Description)
	} else {
		model.Description = types.StringNull()
	}

	if result.CreatorID != nil {
		model.CreatorID = types.StringValue(*result.CreatorID)
	} else {
		model.CreatorID = types.StringNull()
	}

	model.CreatedAt = types.StringValue(result.CreatedAt)

	if result.LastUsedCloudID != nil {
		model.LastUsedCloudID = types.StringValue(*result.LastUsedCloudID)
	} else {
		model.LastUsedCloudID = types.StringNull()
	}

	model.IsDefault = types.BoolValue(result.IsDefault)
	model.DirectoryName = types.StringValue(result.DirectoryName)

	// Only fetch collaborators if they were specified in the configuration
	// This avoids inconsistency with auto-added creator collaborator
	tflog.Debug(ctx, "Checking whether to fetch collaborators", map[string]any{
		"project_id":              projectID,
		"model_collaborators_len": len(model.Collaborators),
	})

	if len(model.Collaborators) > 0 {
		tflog.Debug(ctx, "Fetching collaborators for project", map[string]any{
			"project_id": projectID,
		})
		collaborators, err := r.getCollaborators(ctx, projectID)
		if err != nil {
			tflog.Warn(ctx, "Failed to get collaborators", map[string]any{
				"project_id": projectID,
				"error":      err.Error(),
			})
			// Continue without collaborators rather than failing
			model.Collaborators = []ProjectCollaboratorModel{}
		} else {
			tflog.Debug(ctx, "Successfully fetched collaborators", map[string]any{
				"project_id": projectID,
				"count":      len(collaborators),
			})
			model.Collaborators = collaborators
		}
	} else {
		tflog.Debug(ctx, "Skipping collaborator fetch (none specified in config)", map[string]any{
			"project_id": projectID,
		})
	}

	return nil
}

// getCollaborators fetches the list of collaborators for a project.
func (r *ProjectResource) getCollaborators(ctx context.Context, projectID string) ([]ProjectCollaboratorModel, error) {
	tflog.Debug(ctx, "Fetching collaborators", map[string]any{
		"project_id": projectID,
	})

	// Pages through every page rather than just the first, so a project with
	// more collaborators than fit on one page doesn't silently drop the rest
	// on every read/sync.
	results, err := PaginatedRequest(
		ctx, r.client, fmt.Sprintf("/api/v2/projects/%s/collaborators/users", projectID), nil,
		func(body []byte) ([]ProjectCollaboratorResult, *string, error) {
			var listResp ProjectCollaboratorListResponse
			if err := json.Unmarshal(body, &listResp); err != nil {
				return nil, nil, fmt.Errorf("failed to unmarshal collaborators response: %w", err)
			}
			return listResp.Results, listResp.Metadata.NextPagingToken, nil
		},
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get collaborators: %w", err)
	}

	tflog.Debug(ctx, "Parsed collaborators response", map[string]any{
		"project_id": projectID,
		"count":      len(results),
	})

	// Map to model
	collaborators := make([]ProjectCollaboratorModel, 0, len(results))
	for i, collab := range results {
		tflog.Debug(ctx, "Mapping collaborator", map[string]any{
			"index":            i,
			"email":            collab.Value.Email,
			"permission_level": collab.PermissionLevel,
			"identity_id":      collab.ID,
			"user_id":          collab.Value.ID,
		})
		collaborators = append(collaborators, ProjectCollaboratorModel{
			Email:           types.StringValue(collab.Value.Email),
			PermissionLevel: types.StringValue(collab.PermissionLevel),
			IdentityID:      types.StringValue(collab.ID),
			UserID:          types.StringValue(collab.Value.ID),
		})
	}

	tflog.Debug(ctx, "Returning collaborators", map[string]any{
		"project_id": projectID,
		"count":      len(collaborators),
	})

	return collaborators, nil
}

// createCollaborators batch creates collaborators for a project.
func (r *ProjectResource) createCollaborators(ctx context.Context, projectID string, collaborators []ProjectCollaboratorModel) error {
	if len(collaborators) == 0 {
		return nil
	}

	tflog.Debug(ctx, "Creating collaborators", map[string]any{
		"project_id": projectID,
		"count":      len(collaborators),
	})

	// Build request
	entries := make(ProjectCollaboratorBatchRequest, 0, len(collaborators))
	for _, collab := range collaborators {
		entries = append(entries, ProjectCollaboratorEntry{
			Value: struct {
				Email string `json:"email"`
			}{
				Email: collab.Email.ValueString(),
			},
			PermissionLevel: collab.PermissionLevel.ValueString(),
		})
	}

	reqBody, err := MarshalRequestBody(entries)
	if err != nil {
		return fmt.Errorf("failed to serialize collaborators request: %w", err)
	}

	_, err = DoRequestRaw(
		ctx,
		r.client,
		"POST",
		fmt.Sprintf("/api/v2/projects/%s/collaborators/users/batch_create", projectID),
		reqBody,
		http.StatusOK,
		http.StatusNoContent,
		http.StatusCreated,
		http.StatusConflict, // Accept 409 Conflict as success
	)
	if err != nil {
		// Check if it's a 409 Conflict (already exists)
		if strings.Contains(err.Error(), "409") {
			tflog.Info(ctx, "Collaborator already exists (409), treating as success", map[string]any{
				"project_id": projectID,
			})
			return nil
		}
		return fmt.Errorf("failed to create collaborators: %w", err)
	}

	tflog.Info(ctx, "Collaborators created successfully", map[string]any{
		"project_id": projectID,
		"count":      len(entries),
	})

	return nil
}

// syncCollaborators reconciles collaborator changes between plan and state.
func (r *ProjectResource) syncCollaborators(ctx context.Context, projectID string, planned, current []ProjectCollaboratorModel) error {
	// Build maps for comparison
	planMap := make(map[string]ProjectCollaboratorModel)
	for _, collab := range planned {
		planMap[collab.Email.ValueString()] = collab
	}

	currentMap := make(map[string]ProjectCollaboratorModel)
	for _, collab := range current {
		currentMap[collab.Email.ValueString()] = collab
	}

	// Determine adds, updates, removes
	var toAdd []ProjectCollaboratorModel
	var toUpdate []ProjectCollaboratorModel
	var toRemove []ProjectCollaboratorModel

	// Find adds and updates
	for email, planCollab := range planMap {
		if currentCollab, exists := currentMap[email]; exists {
			// Check if permission changed
			if currentCollab.PermissionLevel.ValueString() != planCollab.PermissionLevel.ValueString() {
				planCollab.IdentityID = currentCollab.IdentityID // Preserve identity_id for update
				toUpdate = append(toUpdate, planCollab)
			}
		} else {
			toAdd = append(toAdd, planCollab)
		}
	}

	// Find removes
	for email, currentCollab := range currentMap {
		if _, exists := planMap[email]; !exists {
			toRemove = append(toRemove, currentCollab)
		}
	}

	// Execute changes
	if len(toAdd) > 0 {
		tflog.Info(ctx, "Adding collaborators", map[string]any{"count": len(toAdd)})
		if err := r.createCollaborators(ctx, projectID, toAdd); err != nil {
			return fmt.Errorf("failed to add collaborators: %w", err)
		}
	}

	for _, collab := range toUpdate {
		tflog.Info(ctx, "Updating collaborator permission", map[string]any{
			"email":      collab.Email.ValueString(),
			"permission": collab.PermissionLevel.ValueString(),
		})

		updateReq := ProjectCollaboratorUpdateRequest{
			PermissionLevel: collab.PermissionLevel.ValueString(),
		}

		reqBody, err := MarshalRequestBody(updateReq)
		if err != nil {
			return fmt.Errorf("failed to serialize update request: %w", err)
		}

		identityID := collab.IdentityID.ValueString()
		_, err = DoRequestRaw(
			ctx,
			r.client,
			"PUT",
			fmt.Sprintf("/api/v2/projects/%s/collaborators/%s", projectID, identityID),
			reqBody,
			http.StatusOK,
			http.StatusNoContent,
		)
		if err != nil {
			return fmt.Errorf("failed to update collaborator %s: %w", collab.Email.ValueString(), err)
		}
	}

	for _, collab := range toRemove {
		tflog.Info(ctx, "Removing collaborator", map[string]any{"email": collab.Email.ValueString()})

		identityID := collab.IdentityID.ValueString()
		_, err := DoRequestRaw(
			ctx,
			r.client,
			"DELETE",
			fmt.Sprintf("/api/v2/projects/%s/collaborators/%s", projectID, identityID),
			nil,
			http.StatusOK,
			http.StatusNoContent,
			http.StatusNotFound,
		)
		if err != nil {
			return fmt.Errorf("failed to remove collaborator %s: %w", collab.Email.ValueString(), err)
		}
	}

	return nil
}
